### ISSUE TITLE
Case-insensitive search

### ISSUE THREAD

**Issue by Dziolas** [SCOAP3/scoap3-next#19]
Currently, the search expects the string precisely written in a certain way (e.g. country: Switzerland). We should give more flexibility (e.g. ignore capitals) so that one could search for switzerland instead.

We should try to be user-friendly for the most common searches in the way, that you can simply enter an expression and the system detects what we try to search for. e.g. if we enter a DOI, the search should understand the string and search for DOI instead of expecting the user to enter DOI: ...

SCOAP3/scoap3#99

**Comment by nyirit** [comment]
fixed in 1e5d2ac

**Comment by oxmynx** [comment]
In addition to the case sensitivity of the search string itself (i.e. switzerland or Switzerland) we should also ignore cases in the field name. At the moment the search Country:switzerland doesn't work as Country with a capital "C" is not recognised.

**Comment by nyirit** [comment]
As far as I can tell there is no clean way to ignore case sensitivity of field names. 

However we could override the [search_factory_imp](https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest/config.py#L109) property and then use our own `facets_factory` instead of the [original](https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest/query.py#L48).

Or we can create an alias for frequently used versions, eg. with uppercase first letters.
