### ISSUE TITLE
CrossRef check seems unreliable (1-3 days)

### ISSUE THREAD

**Issue by oxmynx** [SCOAP3/scoap3-next#241]
The recent failure in harvesting was not properly reported in CrossRef. E.g. still today no missing articles for JHEP were visible in the check despite no harvesting for 12 days.

**Comment by nyirit** [comment]
Should check only for these arxiv categories instead of `hep-*`: hep-ex, hep-lat, hep-ph & hep-th

These 4 categories are the same for all journals except 1. Springer once( JHEP & EPJC) .&  Elsevier (NPB & PLB)- there we accept all categories and we need to have all articles published in those journals

**Comment by nyirit** [comment]
Further investigation is needed why exactly this happens.
Based on a quick look on the logs it's possible that http queries time out sometimes.
**1-3 days**
